# Generated by Django 4.2.11 on 2024-04-10 04:23
# Django
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """ """

    dependencies = [
        ("georgeforge", "0002_alter_general_options_forsale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forsale",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
    ]
