# Generated by Django 4.2.21 on 2025-05-30 09:51

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("georgeforge", "0009_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, max_length=4096, verbose_name="Notes"),
        ),
    ]
