# Generated by Django 4.2.21 on 2025-05-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georgeforge', '0010_alter_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='forsale',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deposit per unit', max_digits=15, verbose_name='Deposit'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid', max_digits=15, verbose_name='Amount Paid'),
        ),
    ]
