# Generated by Django 4.2.21 on 2025-05-30 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0010_alter_eveindustryactivityduration_eve_type_and_more'),
        ('georgeforge', '0011_forsale_deposit_order_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.TextField(max_length=32, null=True, verbose_name='Friendly Name')),
                ('enabled', models.BooleanField(default=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eveuniverse.evesolarsystem', verbose_name='Solar System')),
            ],
        ),
    ]
