# Generated by Django 4.2.21 on 2025-05-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0010_alter_eveindustryactivityduration_eve_type_and_more'),
        ('georgeforge', '0012_deliverysystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverysystem',
            field=models.ForeignKey(default=30000142, on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.evesolarsystem', verbose_name='Delivery System'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverysystem',
            name='friendly_name',
            field=models.TextField(blank=True, default=None, max_length=32, null=True, verbose_name='Friendly Name'),
        ),
        migrations.AlterField(
            model_name='deliverysystem',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.evesolarsystem', verbose_name='Solar System'),
        ),
    ]
