# Generated by Django 4.2.21 on 2025-06-01 08:41

# Django
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("georgeforge", "0013_order_deliverysystem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Deposit required per unit",
                max_digits=15,
                verbose_name="Deposit required per unit",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="forsale",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost per unit",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost per unit",
                max_digits=15,
                verbose_name="Price per unit",
            ),
        ),
    ]
