# Generated by Django 4.2.21 on 2025-06-01 09:07

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "georgeforge",
            "0014_order_deposit_order_quantity_alter_forsale_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="totalcost",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Total Order cost",
                max_digits=15,
                verbose_name="Total Order cost",
            ),
            preserve_default=False,
        ),
    ]
