# Generated by Django 4.2.21 on 2025-06-02 10:03

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("georgeforge", "0016_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (10, "Pending"),
                    (20, "Awaiting Deposit"),
                    (30, "Building Parts"),
                    (35, "Building Hull"),
                    (40, "Contract Up"),
                    (50, "Delivered"),
                    (60, "Rejected"),
                ],
                verbose_name="Status",
            ),
        ),
    ]
