# Generated by Django 4.2.23 on 2025-07-24 02:29

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("georgeforge", "0017_alter_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverysystem",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="forsale",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"default_permissions": ()},
        ),
    ]
