# Generated by Django 4.2.20 on 2025-07-24 04:43

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "georgeforge",
            "0018_alter_deliverysystem_options_alter_forsale_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="on_behalf_of",
            field=models.CharField(
                blank=True,
                help_text="EVE name of person you are ordering on behalf of",
                max_length=37,
                null=True,
                verbose_name="On behalf of",
            ),
        ),
    ]
