# Generated by Django 4.2.20 on 2025-07-24 05:15

# Django
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("georgeforge", "0019_order_on_behalf_of"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Deposit required per unit",
                max_digits=25,
                verbose_name="Deposit required per unit",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount paid",
                max_digits=25,
                verbose_name="Amount Paid",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="totalcost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total Order cost",
                max_digits=25,
                verbose_name="Total Order cost",
            ),
        ),
    ]
